### ISSUE TITLE
Build goes into endless loop and craches

### ISSUE THREAD

**Issue by sergeykad** [iwarapter/gradle-sonar-packaging-plugin#7] opened 2015-11-26 15:00 UTC
The plugin writes `The following dependencies should be defined with scope 'provided': [log4j]` in a loop for some time and then crashes.

After I added the following configuration execution continued to the _pluginPackaging_ stage and failed with `StackOverflowError`

``` Groovy
configurations {
    compile.exclude group: 'log4j', module: 'log4j'
}
```

The stacktrace:

```
* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':pluginPackaging'.
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(Exec
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActi
        at org.gradle.api.internal.tasks.execution.PostExecutionAnalysisTaskExecuter.execute(Post
        at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateT
        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskE
        at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipE
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTask
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskE
        at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteA
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(
        at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.processTask
        at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.run(Abstrac
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor.process(DefaultTaskPlanExecutor
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter.execute(DefaultTaskGraphExecut
        at org.gradle.execution.SelectedTaskExecutionAction.execute(SelectedTaskExecutionAction.j
        at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:37)
        at org.gradle.execution.DefaultBuildExecuter.access$000(DefaultBuildExecuter.java:23)
        at org.gradle.execution.DefaultBuildExecuter$1.proceed(DefaultBuildExecuter.java:43)
        at org.gradle.execution.DryRunBuildExecutionAction.execute(DryRunBuildExecutionAction.jav
        at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:37)
        at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:30)
        at org.gradle.initialization.DefaultGradleLauncher$4.run(DefaultGradleLauncher.java:154)
        at org.gradle.internal.Factories$1.create(Factories.java:22)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationEx
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationEx
        at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.ja
        at org.gradle.initialization.DefaultGradleLauncher.access$200(DefaultGradleLauncher.java:
        at org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradleLauncher.java:99
        at org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradleLauncher.java:93
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationEx
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationEx
        at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:93)
        at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:82)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter$DefaultBuildController.run(InPro
        at org.gradle.tooling.internal.provider.ExecuteBuildActionRunner.run(ExecuteBuildActionRu
        at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:
        at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExec
        at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExec
        at org.gradle.launcher.exec.ContinuousBuildActionExecuter.execute(ContinuousBuildActionEx
        at org.gradle.launcher.exec.ContinuousBuildActionExecuter.execute(ContinuousBuildActionEx
        at org.gradle.launcher.daemon.server.exec.ExecuteBuild.doBuild(ExecuteBuild.java:52)
        at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExec
        at org.gradle.launcher.daemon.server.exec.WatchForDisconnection.execute(WatchForDisconnec
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExec
        at org.gradle.launcher.daemon.server.exec.ResetDeprecationLogger.execute(ResetDeprecation
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExec
        at org.gradle.launcher.daemon.server.exec.RequestStopIfSingleUsedDaemon.execute(RequestSt
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExec
        at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.ja
        at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.ja
        at org.gradle.util.Swapper.swap(Swapper.java:38)
        at org.gradle.launcher.daemon.server.exec.ForwardClientInput.execute(ForwardClientInput.j
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExec
        at org.gradle.launcher.daemon.server.health.DaemonHealthTracker.execute(DaemonHealthTrack
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExec
        at org.gradle.launcher.daemon.server.exec.LogToClient.doBuild(LogToClient.java:66)
        at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExec
        at org.gradle.launcher.daemon.server.exec.EstablishBuildEnvironment.doBuild(EstablishBuil
        at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExec
        at org.gradle.launcher.daemon.server.health.HintGCAfterBuild.execute(HintGCAfterBuild.jav
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExec
        at org.gradle.launcher.daemon.server.exec.StartBuildOrRespondWithBusy$1.run(StartBuildOrR
        at org.gradle.launcher.daemon.server.DaemonStateCoordinator$1.run(DaemonStateCoordinator.
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(Executo
        at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:
Caused by: java.lang.StackOverflowError
        at org.gradle.internal.classloader.FilteringClassLoader.getResource(FilteringClassLoader.
        at com.iadams.gradle.plugins.core.DependencyQuery.getPomPackagingType(DependencyQuery.gro
        at com.iadams.gradle.plugins.core.DependencyQuery$getPomPackagingType$4.callCurrent(Unkno
        at com.iadams.gradle.plugins.core.DependencyQuery.isSonarPlugin(DependencyQuery.groovy:18
        at com.iadams.gradle.plugins.core.DependencyQuery$isSonarPlugin$3.callCurrent(Unknown Sou
        at com.iadams.gradle.plugins.core.DependencyQuery.getNotProvidedDependencies(DependencyQu
        at com.iadams.gradle.plugins.core.DependencyQuery$getNotProvidedDependencies$1.call(Unkno
        at com.iadams.gradle.plugins.tasks.PackagePluginTask.copy(PackagePluginTask.groovy:159)
        at com.iadams.gradle.plugins.tasks.PackagePluginTask.copy(PackagePluginTask.groovy:186)
        at com.iadams.gradle.plugins.tasks.PackagePluginTask.copy(PackagePluginTask.groovy:186)
        at com.iadams.gradle.plugins.tasks.PackagePluginTask.copy(PackagePluginTask.groovy:186)
        at com.iadams.gradle.plugins.tasks.PackagePluginTask.copy(PackagePluginTask.groovy:186)
        at com.iadams.gradle.plugins.tasks.PackagePluginTask.copy(PackagePluginTask.groovy:186)
        at com.iadams.gradle.plugins.tasks.PackagePluginTask.copy(PackagePluginTask.groovy:186)
        at com.iadams.gradle.plugins.tasks.PackagePluginTask.copy(PackagePluginTask.groovy:186)
        at com.iadams.gradle.plugins.tasks.PackagePluginTask.copy(PackagePluginTask.groovy:186)
        at com.iadams.gradle.plugins.tasks.PackagePluginTask.copy(PackagePluginTask.groovy:186)
        at com.iadams.gradle.plugins.tasks.PackagePluginTask.copy(PackagePluginTask.groovy:186)
        at com.iadams.gradle.plugins.tasks.PackagePluginTask.copy(PackagePluginTask.groovy:186)
        at com.iadams.gradle.plugins.tasks.PackagePluginTask.copy(PackagePluginTask.groovy:186)
        at com.iadams.gradle.plugins.tasks.PackagePluginTask.copy(PackagePluginTask.groovy:186)
        at com.iadams.gradle.plugins.tasks.PackagePluginTask.copy(PackagePluginTask.groovy:186)
        at com.iadams.gradle.plugins.tasks.PackagePluginTask.copy(PackagePluginTask.groovy:186)
        at com.iadams.gradle.plugins.tasks.PackagePluginTask.copy(PackagePluginTask.groovy:186)
        at com.iadams.gradle.plugins.tasks.PackagePluginTask.copy(PackagePluginTask.groovy:186)
        at com.iadams.gradle.plugins.tasks.PackagePluginTask.copy(PackagePluginTask.groovy:186)
        at com.iadams.gradle.plugins.tasks.PackagePluginTask.copy(PackagePluginTask.groovy:186)
        at com.iadams.gradle.plugins.tasks.PackagePluginTask.copy(PackagePluginTask.groovy:186)
        at com.iadams.gradle.plugins.tasks.PackagePluginTask.copy(PackagePluginTask.groovy:186)
        at com.iadams.gradle.plugins.tasks.PackagePluginTask.copy(PackagePluginTask.groovy:186)
        at com.iadams.gradle.plugins.tasks.PackagePluginTask.copy(PackagePluginTask.groovy:186)
        at com.iadams.gradle.plugins.tasks.PackagePluginTask.copy(PackagePluginTask.groovy:186)
        at com.iadams.gradle.plugins.tasks.PackagePluginTask.copy(PackagePluginTask.groovy:186)
        at com.iadams.gradle.plugins.tasks.PackagePluginTask.copy(PackagePluginTask.groovy:186)
        at com.iadams.gradle.plugins.tasks.PackagePluginTask.copy(PackagePluginTask.groovy:186)
        at com.iadams.gradle.plugins.tasks.PackagePluginTask.copy(PackagePluginTask.groovy:186)
        at com.iadams.gradle.plugins.tasks.PackagePluginTask.copy(PackagePluginTask.groovy:186)
        at com.iadams.gradle.plugins.tasks.PackagePluginTask.copy(PackagePluginTask.groovy:186)
        at com.iadams.gradle.plugins.tasks.PackagePluginTask.copy(PackagePluginTask.groovy:186)
        at com.iadams.gradle.plugins.tasks.PackagePluginTask.copy(PackagePluginTask.groovy:186)
        at com.iadams.gradle.plugins.tasks.PackagePluginTask.copy(PackagePluginTask.groovy:186)
        at com.iadams.gradle.plugins.tasks.PackagePluginTask.copy(PackagePluginTask.groovy:186)
        at com.iadams.gradle.plugins.tasks.PackagePluginTask.copy(PackagePluginTask.groovy:186)
        at com.iadams.gradle.plugins.tasks.PackagePluginTask.copy(PackagePluginTask.groovy:186)
        at com.iadams.gradle.plugins.tasks.PackagePluginTask.copy(PackagePluginTask.groovy:186)
        at com.iadams.gradle.plugins.tasks.PackagePluginTask.copy(PackagePluginTask.groovy:186)
        at com.iadams.gradle.plugins.tasks.PackagePluginTask.copy(PackagePluginTask.groovy:186)
        at com.iadams.gradle.plugins.tasks.PackagePluginTask.copy(PackagePluginTask.groovy:186)
        at com.iadams.gradle.plugins.tasks.PackagePluginTask.copy(PackagePluginTask.groovy:186)
        at com.iadams.gradle.plugins.tasks.PackagePluginTask.copy(PackagePluginTask.groovy:186)
        at com.iadams.gradle.plugins.tasks.PackagePluginTask.copy(PackagePluginTask.groovy:186)
        at com.iadams.gradle.plugins.tasks.PackagePluginTask.copy(PackagePluginTask.groovy:186)
        at com.iadams.gradle.plugins.tasks.PackagePluginTask.copy(PackagePluginTask.groovy:186)
        at com.iadams.gradle.plugins.tasks.PackagePluginTask.copy(PackagePluginTask.groovy:186)
        at com.iadams.gradle.plugins.tasks.PackagePluginTask.copy(PackagePluginTask.groovy:186)
        at com.iadams.gradle.plugins.tasks.PackagePluginTask.copy(PackagePluginTask.groovy:186)
        at com.iadams.gradle.plugins.tasks.PackagePluginTask.copy(PackagePluginTask.groovy:186)
        at com.iadams.gradle.plugins.tasks.PackagePluginTask.copy(PackagePluginTask.groovy:186)
        at com.iadams.gradle.plugins.tasks.PackagePluginTask.copy(PackagePluginTask.groovy:186)
        at com.iadams.gradle.plugins.tasks.PackagePluginTask.copy(PackagePluginTask.groovy:186)
        at com.iadams.gradle.plugins.tasks.PackagePluginTask.copy(PackagePluginTask.groovy:186)
        at com.iadams.gradle.plugins.tasks.PackagePluginTask.copy(PackagePluginTask.groovy:186)
        at com.iadams.gradle.plugins.tasks.PackagePluginTask.copy(PackagePluginTask.groovy:186)
        at com.iadams.gradle.plugins.tasks.PackagePluginTask.copy(PackagePluginTask.groovy:186)
        at com.iadams.gradle.plugins.tasks.PackagePluginTask.copy(PackagePluginTask.groovy:186)
        at com.iadams.gradle.plugins.tasks.PackagePluginTask.copy(PackagePluginTask.groovy:186)
        at com.iadams.gradle.plugins.tasks.PackagePluginTask.copy(PackagePluginTask.groovy:186)
        at com.iadams.gradle.plugins.tasks.PackagePluginTask.copy(PackagePluginTask.groovy:186)
        at com.iadams.gradle.plugins.tasks.PackagePluginTask.copy(PackagePluginTask.groovy:186)
        at com.iadams.gradle.plugins.tasks.PackagePluginTask.copy(PackagePluginTask.groovy:186)
        at com.iadams.gradle.plugins.tasks.PackagePluginTask.copy(PackagePluginTask.groovy:186)
        at com.iadams.gradle.plugins.tasks.PackagePluginTask.copy(PackagePluginTask.groovy:186)
        at com.iadams.gradle.plugins.tasks.PackagePluginTask.copy(PackagePluginTask.groovy:186)
        at com.iadams.gradle.plugins.tasks.PackagePluginTask.copy(PackagePluginTask.groovy:186)
        at com.iadams.gradle.plugins.tasks.PackagePluginTask.copy(PackagePluginTask.groovy:186)
        at com.iadams.gradle.plugins.tasks.PackagePluginTask.copy(PackagePluginTask.groovy:186)
        at com.iadams.gradle.plugins.tasks.PackagePluginTask.copy(PackagePluginTask.groovy:186)
        at com.iadams.gradle.plugins.tasks.PackagePluginTask.copy(PackagePluginTask.groovy:186)
        at com.iadams.gradle.plugins.tasks.PackagePluginTask.copy(PackagePluginTask.groovy:186)
        at com.iadams.gradle.plugins.tasks.PackagePluginTask.copy(PackagePluginTask.groovy:186)
        at com.iadams.gradle.plugins.tasks.PackagePluginTask.copy(PackagePluginTask.groovy:186)
        at com.iadams.gradle.plugins.tasks.PackagePluginTask.copy(PackagePluginTask.groovy:186)
        at com.iadams.gradle.plugins.tasks.PackagePluginTask.copy(PackagePluginTask.groovy:186)
        at com.iadams.gradle.plugins.tasks.PackagePluginTask.copy(PackagePluginTask.groovy:186)
        at com.iadams.gradle.plugins.tasks.PackagePluginTask.copy(PackagePluginTask.groovy:186)
        at com.iadams.gradle.plugins.tasks.PackagePluginTask.copy(PackagePluginTask.groovy:186)
        at com.iadams.gradle.plugins.tasks.PackagePluginTask.copy(PackagePluginTask.groovy:186)
        at com.iadams.gradle.plugins.tasks.PackagePluginTask.copy(PackagePluginTask.groovy:186)
        at com.iadams.gradle.plugins.tasks.PackagePluginTask.copy(PackagePluginTask.groovy:186)
        at com.iadams.gradle.plugins.tasks.PackagePluginTask.copy(PackagePluginTask.groovy:186)
        at com.iadams.gradle.plugins.tasks.PackagePluginTask.copy(PackagePluginTask.groovy:186)
        at com.iadams.gradle.plugins.tasks.PackagePluginTask.copy(PackagePluginTask.groovy:186)
        at com.iadams.gradle.plugins.tasks.PackagePluginTask.copy(PackagePluginTask.groovy:186)
        at com.iadams.gradle.plugins.tasks.PackagePluginTask.copy(PackagePluginTask.groovy:186)
        at com.iadams.gradle.plugins.tasks.PackagePluginTask.copy(PackagePluginTask.groovy:186)
        at com.iadams.gradle.plugins.tasks.PackagePluginTask.copy(PackagePluginTask.groovy:186)
        at com.iadams.gradle.plugins.tasks.PackagePluginTask.copy(PackagePluginTask.groovy:186)
        at com.iadams.gradle.plugins.tasks.PackagePluginTask.copy(PackagePluginTask.groovy:186)
        at com.iadams.gradle.plugins.tasks.PackagePluginTask.copy(PackagePluginTask.groovy:186)
        at com.iadams.gradle.plugins.tasks.PackagePluginTask.copy(PackagePluginTask.groovy:186)
        at com.iadams.gradle.plugins.tasks.PackagePluginTask.copy(PackagePluginTask.groovy:186)
        at com.iadams.gradle.plugins.tasks.PackagePluginTask.copy(PackagePluginTask.groovy:186)
        at com.iadams.gradle.plugins.tasks.PackagePluginTask.copy(PackagePluginTask.groovy:186)
        at com.iadams.gradle.plugins.tasks.PackagePluginTask.copy(PackagePluginTask.groovy:186)
        at com.iadams.gradle.plugins.tasks.PackagePluginTask.copy(PackagePluginTask.groovy:186)
        at com.iadams.gradle.plugins.tasks.PackagePluginTask.copy(PackagePluginTask.groovy:186)
        at com.iadams.gradle.plugins.tasks.PackagePluginTask.copy(PackagePluginTask.groovy:186)
        at com.iadams.gradle.plugins.tasks.PackagePluginTask.copy(PackagePluginTask.groovy:186)
        at com.iadams.gradle.plugins.tasks.PackagePluginTask.copy(PackagePluginTask.groovy:186)
        at com.iadams.gradle.plugins.tasks.PackagePluginTask.copy(PackagePluginTask.groovy:186)
        at com.iadams.gradle.plugins.tasks.PackagePluginTask.copy(PackagePluginTask.groovy:186)
        at com.iadams.gradle.plugins.tasks.PackagePluginTask.copy(PackagePluginTask.groovy:186)
        at com.iadams.gradle.plugins.tasks.PackagePluginTask.copy(PackagePluginTask.groovy:186)
        at com.iadams.gradle.plugins.tasks.PackagePluginTask.copy(PackagePluginTask.groovy:186)
        at com.iadams.gradle.plugins.tasks.PackagePluginTask.copy(PackagePluginTask.groovy:186)
        at com.iadams.gradle.plugins.tasks.PackagePluginTask.copy(PackagePluginTask.groovy:186)
        at com.iadams.gradle.plugins.tasks.PackagePluginTask.copy(PackagePluginTask.groovy:186)
        at com.iadams.gradle.plugins.tasks.PackagePluginTask.copy(PackagePluginTask.groovy:186)
```

**Comment by iwarapter** [comment] 2015-11-26 18:41
Which version of gradle/plugin are you using?

**Comment by sergeykad** [comment] 2015-11-29 07:18
Gradle 2.9, com.iadams.sonar-packaging 0.1.2, JDK 1.7.0_79

I checked with older Gradle versions now. It works on 2.7, but fails on newer versions.

**Comment by iwarapter** [comment] 2015-11-29 10:55
Have been able to reproduce, will hopefully have it fixed soon.

**Comment by iwarapter** [comment] 2015-12-01 23:20
I have published a snapshot if you'd like to confirm the fix:
https://github.com/iwarapter/gradle-sonar-packaging-plugin/releases/tag/0.1.3-alpha

**Comment by timonsdad** [comment] 2015-12-02 20:36
I just started experiencing the same issue and stumbled across this thread.  I have confirmed that the issue is fixed in my environment.

**Comment by iwarapter** [comment] 2015-12-02 20:38
Cool i'll publish the plugin shortly.

**Comment by timonsdad** [comment] 2015-12-02 20:38
Thanks.  Most appreciated.

**Comment by sergeykad** [comment] 2015-12-03 14:41
Thanks a lot, but I am getting errors if I set the plugin version to "0.1.3"

I tried both new and old plugin notation.
Is it available in the repository(es)?

**Comment by iwarapter** [comment] 2015-12-03 15:02
no i havnt had a chance to publish it yet (stuck in a conference)

**Comment by iwarapter** [comment] 2015-12-06 16:08
This has been published, cheers for your help.

**Closed as completed by iwarapter** 2015-12-06 16:08 UTC
